language:
  - node_js
node_js:
  - node
  - "7.2.1"
install:
  - npm install
script:
  - npm test
addons:
  code_climate:
    repo_token: 879d971d780837ded4d70eff9d963927d609a383ae6c2377486e64a9dbd33694
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
